"use client";

import { useEffect, useRef } from "react";
import Image from "next/image";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

interface ProjectItem {
  id: string;
  tag: string;
  year: string;
  title: string;
  subtitle: string;
  description: string;
  metrics: string[];
  tags: string[];
  accentColor: string;
  image: string;
  link: string;
}

const PROJECTS: ProjectItem[] = [
  {
    id: "prismax-maker",
    tag: "PRISMAX ECOSYSTEM",
    year: "2024",
    title: "PrismaX Content Maker & Canvas Suite",
    subtitle: "High-performance browser graphics generator for creators",
    description:
      "Engineered an automated creator suite designed to make Web3 asset and thumbnail generation effortless. Features interactive canvas layers, custom vector export, and instant social asset rendering.",
    metrics: [
      "Sub-16ms GPU canvas rendering speed",
      "Over 45,000+ assets generated by community creators",
      "Zero-latency layer transformation engine",
    ],
    tags: ["React 19", "Next.js", "Canvas API", "WebGL", "TypeScript"],
    accentColor: "rgba(183, 170, 137, 0.9)",
    image: "/project-01.jpg",
    link: "https://x.com/PrismaX_AI",
  },
  {
    id: "contribution-cards",
    tag: "OPEN SOURCE",
    year: "2024",
    title: "Dynamic Contribution Cards & Activity Telemetry",
    subtitle: "Developer activity visualization and card generator",
    description:
      "A developer utility transforming complex git commits and protocol telemetry into publication-ready interactive social cards. Features customizable themes, SVG vector rasterization, and API endpoints.",
    metrics: [
      "3.2x increase in developer social sharing",
      "High-speed SVG & PNG rasterization pipeline",
      "Instant GitHub GraphQL event synchronizer",
    ],
    tags: ["TypeScript", "SVG Engine", "Node.js", "Tailwind CSS"],
    accentColor: "rgba(83, 104, 117, 0.9)",
    image: "/project-02.jpg",
    link: "#",
  },
  {
    id: "event-tracker",
    tag: "COMMUNITY PLATFORM",
    year: "2023",
    title: "PrismaX Protocol Event Tracker & Radar",
    subtitle: "Real-time ecosystem meetup and hackathon aggregator",
    description:
      "A community-driven platform for discovering, tracking, and attending decentralized hackathons and protocol milestones. Built with real-time indexing, instant search, and calendar integration.",
    metrics: [
      "Tracked 120+ global developer events & meetups",
      "Instant fuzzy search with <10ms response time",
      "Fully responsive mobile calendar interface",
    ],
    tags: ["Next.js", "PostgreSQL", "Tailwind", "Event APIs"],
    accentColor: "rgba(140, 128, 101, 0.9)",
    image: "/project-03.jpg",
    link: "#",
  },
  {
    id: "helper-bot",
    tag: "AUTOMATION & INFRA",
    year: "2023",
    title: "Intelligent Community Automation Bot",
    subtitle: "Discord and Telegram automated moderation & onboarding",
    description:
      "An automated bot ecosystem providing 24/7 verification, automated member onboarding, protocol health telemetry, and instant answers to frequently asked community questions.",
    metrics: [
      "Automated 92% of repetitive community inquiries",
      "Protected 50,000+ members from scam vectors",
      "Sub-200ms API response latency across nodes",
    ],
    tags: ["Node.js", "Discord API", "Distributed Workers", "Redis"],
    accentColor: "rgba(92, 43, 53, 0.9)",
    image: "/project-04.jpg",
    link: "#",
  },
];

export function ProjectsSection() {
  const sectionRef = useRef<HTMLElement>(null);
  const cardRefs = useRef<(HTMLDivElement | null)[]>([]);

  useEffect(() => {
    const prefersReducedMotion = window.matchMedia(
      "(prefers-reduced-motion: reduce)"
    ).matches;
    if (prefersReducedMotion) return;

    const ctx = gsap.context(() => {
      cardRefs.current.forEach((card) => {
        if (!card) return;

        gsap.from(card, {
          y: 50,
          opacity: 0,
          duration: 1.1,
          ease: "power2.out",
          scrollTrigger: {
            trigger: card,
            start: "top 82%",
            toggleActions: "play none none reverse",
          },
        });
      });
    }, sectionRef);

    return () => ctx.revert();
  }, []);

  return (
    <section
      id="work"
      ref={sectionRef}
      className="relative z-10 py-16 md:py-24 px-[var(--content-padding)] border-t border-[var(--slate-blue)]/30"
      aria-label="Curated Work & Featured Case Studies"
    >
      <div className="max-w-6xl mx-auto">
        {/* Section Header (Inspired by personalfolio.framer.website) */}
        <div className="mb-14 md:mb-20">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-[var(--slate-blue)]/60 bg-[var(--bg-storm-deep)]/60 text-micro tracking-[0.2em] text-[var(--muted-bronze)] uppercase font-medium mb-3">
            <span>CURATED WORK</span>
          </div>

          <h2 className="text-section font-bold tracking-tight text-[var(--warm-ivory)] leading-tight mb-3">
            Featured Case Studies
          </h2>

          <p className="text-body text-[var(--weathered-stone)] max-w-2xl font-light">
            Compilation of digital products, developer tooling, and decentralized applications built with meticulous craft and measurable impact.
          </p>
        </div>

        {/* Case Studies Cards Stack */}
        <div className="space-y-12 md:space-y-16">
          {PROJECTS.map((project, i) => (
            <div
              key={project.id}
              ref={(el) => {
                cardRefs.current[i] = el;
              }}
              className="group relative rounded-2xl md:rounded-3xl border border-[var(--slate-blue)]/50 bg-[var(--bg-storm-deep)]/40 hover:bg-[var(--bg-storm-deep)]/70 hover:border-[var(--metallic-highlight)]/50 transition-all duration-500 overflow-hidden shadow-2xl backdrop-blur-sm p-6 md:p-10"
            >
              {/* Subtle Ambient Glow */}
              <div
                className="absolute -right-20 -top-20 w-80 h-80 rounded-full opacity-10 group-hover:opacity-20 transition-opacity duration-700 pointer-events-none"
                style={{
                  background: `radial-gradient(circle, ${project.accentColor} 0%, transparent 70%)`,
                  filter: "blur(40px)",
                }}
                aria-hidden="true"
              />

              <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 md:gap-12 items-center">
                {/* Left Column: Project Details & Metrics */}
                <div className="lg:col-span-6 flex flex-col justify-between h-full">
                  <div>
                    {/* Tag & Year Pill */}
                    <div className="flex items-center gap-2.5 mb-4">
                      <span className="text-[0.68rem] px-2.5 py-0.5 rounded-full border border-[var(--slate-blue)] bg-[var(--bg-primary)]/80 text-[var(--metallic-highlight)] font-mono tracking-wider uppercase font-medium">
                        {project.tag}
                      </span>
                      <span className="text-[0.68rem] text-[var(--weathered-stone)]/60 font-mono">
                        {project.year}
                      </span>
                    </div>

                    {/* Title & Subtitle */}
                    <h3 className="text-2xl md:text-3xl font-bold text-[var(--warm-ivory)] group-hover:text-[var(--metallic-highlight)] transition-colors duration-300 leading-snug mb-2">
                      {project.title}
                    </h3>
                    <p className="text-small text-[var(--metallic-highlight)]/90 font-medium mb-4">
                      {project.subtitle}
                    </p>

                    {/* Description */}
                    <p className="text-small text-[var(--weathered-stone)] leading-relaxed font-light mb-6">
                      {project.description}
                    </p>

                    {/* Key Outcome Metric Bullets (Inspired by personalfolio) */}
                    <div className="space-y-2 mb-6 p-4 rounded-xl bg-[var(--bg-primary)]/50 border border-[var(--slate-blue)]/40">
                      {project.metrics.map((metric, idx) => (
                        <div key={idx} className="flex items-start gap-2.5 text-[0.78rem] text-[var(--warm-ivory)]/90">
                          <span className="text-[var(--metallic-highlight)] mt-0.5 text-xs">✦</span>
                          <span className="font-light">{metric}</span>
                        </div>
                      ))}
                    </div>

                    {/* Tech Badges */}
                    <div className="flex flex-wrap gap-1.5 mb-6">
                      {project.tags.map((tag) => (
                        <span
                          key={tag}
                          className="text-[0.65rem] px-2.5 py-1 rounded-md border border-[var(--slate-blue)]/40 bg-[var(--bg-primary)]/40 text-[var(--weathered-stone)] font-mono"
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Explore Button */}
                  <div>
                    <a
                      href={project.link}
                      target={project.link.startsWith("http") ? "_blank" : undefined}
                      rel={project.link.startsWith("http") ? "noopener noreferrer" : undefined}
                      className="inline-flex items-center gap-2 text-small tracking-wider uppercase font-medium text-[var(--warm-ivory)] hover:text-[var(--metallic-highlight)] transition-colors group-hover:translate-x-1 duration-300 cursor-pointer"
                    >
                      <span>Explore Project</span>
                      <span className="text-[var(--metallic-highlight)]">→</span>
                    </a>
                  </div>
                </div>

                {/* Right Column: Visual Mockup Showcase */}
                <div className="lg:col-span-6">
                  <div className="relative aspect-[16/10] rounded-xl md:rounded-2xl overflow-hidden border border-[var(--slate-blue)]/40 shadow-inner group/img bg-[var(--bg-primary)]">
                    <Image
                      src={project.image}
                      alt={project.title}
                      fill
                      sizes="(max-width: 1024px) 100vw, 50vw"
                      className="object-cover transition-transform duration-700 ease-out group-hover:scale-105"
                    />

                    {/* Subtle aesthetic gradient overlay */}
                    <div
                      className="absolute inset-0 opacity-40 transition-opacity duration-700 group-hover:opacity-20 pointer-events-none"
                      style={{
                        background:
                          "linear-gradient(135deg, rgba(8,13,20,0.4) 0%, transparent 60%, rgba(16,32,45,0.6) 100%)",
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
